# Generated by Django 3.1.3 on 2020-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destion', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
