# Generated by Django 3.1.3 on 2020-11-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20201125_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=34)),
                ('last_name', models.CharField(max_length=34)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='airline.flight')),
            ],
        ),
    ]
